/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tithi.bookworm;

import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.io.IOException;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class ManageGenre extends javax.swing.JFrame {

    DataBaseConnection db;
    
    public ManageGenre() {
        initComponents();
        setContentPane(new javax.swing.JLabel(new ImageIcon("src/main/resources/Backgrounds/shade13.png")));
        addStuff();
        setStuff();
        db = new DataBaseConnection();
        setList();
    }

    private void addStuff(){
        add(back);add(backL); add(remove);add(add);add(jList1);add(Header);add(jPanel1);
        add(title);add(backL1);add(backL2);
    }
    
    private void setStuff(){
        try {
            backL.setIcon(new ImageIcon(ImageIO.read(new java.io.File("src/main/resources/Icons/blue plus.png")
            ).getScaledInstance(backL.getWidth(), backL.getHeight(),
                    Image.SCALE_SMOOTH)));
            backL1.setIcon(new ImageIcon(ImageIO.read(new java.io.File("src/main/resources/Icons/backgreen.png")
            ).getScaledInstance(backL1.getWidth(), backL1.getHeight(),
                    Image.SCALE_SMOOTH)));
            backL2.setIcon(new ImageIcon(ImageIO.read(new java.io.File("src/main/resources/Icons/red cancel.png")
            ).getScaledInstance(backL2.getWidth(), backL2.getHeight(),
                    Image.SCALE_SMOOTH)));
        } catch (IOException ex) {
            ex.printStackTrace();
        }
            add.setOpaque(false);
            add.setContentAreaFilled(false);
            add.setBorderPainted(false);
            remove.setOpaque(false);
            remove.setContentAreaFilled(false);
            remove.setBorderPainted(false);
            jPanel1.setVisible(false);
            jList1.setFont(new Font("Footlight MT Light", Font.PLAIN, 22));
            jDialog1.setLocationRelativeTo(null);
            jDialog1.getContentPane().setBackground(new Color(0,102,102));
        
    }
    
    private void setList(){
        try {
            db.rs = db.stmt.executeQuery("select * from genre");
            DefaultListModel dlm = new DefaultListModel();
            while(db.rs.next()){
                dlm.addElement(db.rs.getString("genre_name"));
            }
            jList1.setModel(dlm);
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        Header1 = new javax.swing.JLabel();
        newGenre = new javax.swing.JTextField();
        jList1 = new javax.swing.JList();
        add = new javax.swing.JButton();
        remove = new javax.swing.JButton();
        back = new javax.swing.JLabel();
        backL = new javax.swing.JLabel();
        Header = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        backL1 = new javax.swing.JLabel();
        backL2 = new javax.swing.JLabel();

        jDialog1.setAutoRequestFocus(false);
        jDialog1.setBackground(new java.awt.Color(0, 102, 102));
        jDialog1.setUndecorated(true);
        jDialog1.setSize(new java.awt.Dimension(388, 149));
        jDialog1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jDialog1KeyPressed(evt);
            }
        });

        Header1.setFont(new java.awt.Font("Footlight MT Light", 0, 20)); // NOI18N
        Header1.setForeground(new java.awt.Color(255, 255, 255));
        Header1.setText("New genre:");

        newGenre.setFont(new java.awt.Font("Footlight MT Light", 0, 20)); // NOI18N
        newGenre.setForeground(new java.awt.Color(0, 51, 51));
        newGenre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                newGenreKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(Header1)
                .addGap(18, 18, 18)
                .addComponent(newGenre, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Header1)
                    .addComponent(newGenre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setSize(new java.awt.Dimension(750, 800));

        jList1.setBackground(new java.awt.Color(204, 255, 255));
        jList1.setFont(new java.awt.Font("Footlight MT Light", 0, 20)); // NOI18N
        jList1.setForeground(new java.awt.Color(0, 51, 51));

        add.setBackground(new java.awt.Color(204, 204, 255));
        add.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        add.setForeground(new java.awt.Color(255, 255, 255));
        add.setText("Add New Genre");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        remove.setBackground(new java.awt.Color(204, 204, 255));
        remove.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        remove.setForeground(new java.awt.Color(255, 255, 255));
        remove.setText("Remove A Genre");
        remove.setOpaque(false);
        remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeActionPerformed(evt);
            }
        });

        back.setFont(new java.awt.Font("Footlight MT Light", 0, 20)); // NOI18N
        back.setForeground(new java.awt.Color(0, 51, 51));
        back.setText("Back");
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });

        backL.setText("jLabel7");
        backL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backLMouseClicked(evt);
            }
        });

        Header.setFont(new java.awt.Font("Footlight MT Light", 0, 20)); // NOI18N
        Header.setForeground(new java.awt.Color(0, 51, 51));
        Header.setText("List of genre:");

        title.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.darkShadow"));
        title.setFont(new java.awt.Font("Old English Text MT", 0, 28)); // NOI18N
        title.setForeground(new java.awt.Color(0, 51, 51));
        title.setText("Manage Genre");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 437, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 116, Short.MAX_VALUE)
        );

        backL1.setText("jLabel7");
        backL1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backL1MouseClicked(evt);
            }
        });

        backL2.setText("jLabel7");
        backL2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backL2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Header)
                    .addComponent(jList1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(backL, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(add)
                        .addGap(118, 118, 118))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(backL1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(back))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(backL2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(remove)))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(title)
                .addGap(282, 282, 282))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(81, Short.MAX_VALUE)
                .addComponent(title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Header)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(backL, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(add))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(backL2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(remove))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(back)
                            .addComponent(backL1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jList1, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(79, 79, 79))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        jDialog1.setVisible(true); newGenre.setText("");
    }//GEN-LAST:event_addActionPerformed

    private void removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeActionPerformed
        List l = jList1.getSelectedValuesList();
        for(int i=0; i<l.size();i++){
            try {
                db.stmt.executeUpdate("delete from genre where genre_name = '"+l.get(i)+"'");
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        }
        setList();
    }//GEN-LAST:event_removeActionPerformed

    private void backLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backLMouseClicked
        jDialog1.setVisible(true); newGenre.setText("");
    }//GEN-LAST:event_backLMouseClicked

    private void newGenreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_newGenreKeyPressed
        if (evt.getKeyCode()==java.awt.event.KeyEvent.VK_ENTER){
            try {
                String genre = "'"+newGenre.getText()+"'";
                db.stmt.executeUpdate("insert into genre(genre_name) values("+genre+")");
                setList();
            } catch (SQLException ex) {
                ex.printStackTrace();
                String error_mssg = "ORA-00001: unique constraint (IPM.SYS_C0010637) violated";
                if(ex.getMessage().equals(error_mssg)){
                    JOptionPane.showMessageDialog(null, "This genre already exists.");
                }
            }
        jDialog1.setVisible(false);
        }
        if(evt.getKeyCode()==java.awt.event.KeyEvent.VK_ESCAPE){
            jDialog1.setVisible(false);
        }
    }//GEN-LAST:event_newGenreKeyPressed

    private void backL1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backL1MouseClicked
        this.setVisible(false);this.dispose();
        new BookManagement().setVisible(true);
    }//GEN-LAST:event_backL1MouseClicked

    private void backL2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backL2MouseClicked
        List l = jList1.getSelectedValuesList();
        for(int i=0; i<l.size();i++){
            try {
                db.stmt.executeUpdate("delete from genre where genre_name = '"+l.get(i)+"'");
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        }
        setList();
    }//GEN-LAST:event_backL2MouseClicked

    private void jDialog1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jDialog1KeyPressed
        if(evt.getKeyCode()==java.awt.event.KeyEvent.VK_ESCAPE){
            jDialog1.setVisible(false);
        }
    }//GEN-LAST:event_jDialog1KeyPressed

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        this.setVisible(false);this.dispose();
        new BookManagement().setVisible(true);
    }//GEN-LAST:event_backMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageGenre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageGenre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageGenre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageGenre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageGenre().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Header;
    private javax.swing.JLabel Header1;
    private javax.swing.JButton add;
    private javax.swing.JLabel back;
    private javax.swing.JLabel backL;
    private javax.swing.JLabel backL1;
    private javax.swing.JLabel backL2;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField newGenre;
    private javax.swing.JButton remove;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
