/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tithi.bookworm;

import java.awt.Color;
import java.awt.Image;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class ViewBooks extends javax.swing.JFrame {

    DataBaseConnection db;
    public ViewBooks() {
        initComponents();
        setContentPane(new javax.swing.JLabel(new ImageIcon("src/main/resources/Backgrounds/shade7.png")));
        //jDialog1.setLocation(405, 500);
        addStuff();
        setStuff();
        db = new DataBaseConnection();
        setTable("book_id");
        //jDialog1.setVisible(true);
    }

    private void addStuff(){
        add(jScrollPane2); add(title); add(Header); add(idcheck);add(idcheck);
        add(booknamecheck);add(authornamecheck);add(datecheck);
        add(remove); add(Header1); add(backL1);add(back); add(edit); add(Header3);
    }
    
    private void setStuff(){
        try {
            backL1.setIcon(new ImageIcon(ImageIO.read(new java.io.File("src/main/resources/Icons/backgray.png")
            ).getScaledInstance(backL1.getWidth(), backL1.getHeight(),
                    Image.SCALE_SMOOTH)));
            remove.setIcon(new ImageIcon(ImageIO.read(new java.io.File("src/main/resources/Icons/red cancel.png")
            ).getScaledInstance(remove.getWidth(), remove.getHeight(),
                    Image.SCALE_SMOOTH)));
            edit.setIcon(new ImageIcon(ImageIO.read(new java.io.File("src/main/resources/Icons/editred.png")
            ).getScaledInstance(edit.getWidth(), edit.getHeight(),
                    Image.SCALE_SMOOTH)));
        } catch (IOException ex) {
            ex.printStackTrace();
        }
        jDialog2.setLocationRelativeTo(null);
        jDialog2.getContentPane().setBackground(new Color(255,255,204));
        jDialog1.getContentPane().setBackground(new Color(255,255,204));
        yes.setOpaque(false);
        yes.setContentAreaFilled(false);
        yes.setBorderPainted(false);
        cancel.setOpaque(false);
        cancel.setContentAreaFilled(false);
        cancel.setBorderPainted(false);
        idcheck.setSelected(true);
    }
    
    private void setTable(String Sort){
        try {
            DefaultTableModel model = (DefaultTableModel) booklist.getModel();
            model.setRowCount(0);
            String genre = "";
            db.rs = db.stmt.executeQuery("select * from book order by " + Sort);
            while(db.rs.next()){
                int id = db.rs.getInt("book_id");
                List genreid = new ArrayList();
                db.rs2 = db.stmt2.executeQuery("select genre_id from book_genre where book_id = "+id);
                while(db.rs2.next()){
                    genreid.add(db.rs2.getInt("genre_id"));
                }
                if(genreid.size() > 0){
                    db.rs2 = db.stmt2.executeQuery("select genre_name from genre where genre_id = "+genreid.get(0));
                    db.rs2.next();
                    genre = db.rs2.getString("genre_name");
                    for(int i=1; i<genreid.size();i++){
                        db.rs2 = db.stmt2.executeQuery("select genre_name from genre where genre_id = "+genreid.get(i));
                        db.rs2.next();
                        genre = genre + ", "+ db.rs2.getString("genre_name");
                }}
                ((DefaultTableModel)booklist.getModel()).addRow(new Object[]{id,
                    db.rs.getString("book_name"),db.rs.getString("author_name"), genre,
                    db.rs.getDate("release_date"),db.rs.getString("description")});
                ((AbstractTableModel)booklist.getModel()).fireTableDataChanged();
            }
        } catch (SQLException ex) {
           ex.printStackTrace();
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sorts = new javax.swing.ButtonGroup();
        jDialog1 = new javax.swing.JDialog();
        Header4 = new javax.swing.JLabel();
        Header5 = new javax.swing.JLabel();
        Header6 = new javax.swing.JLabel();
        Header7 = new javax.swing.JLabel();
        Header8 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        AuthorName = new javax.swing.JEditorPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        DescRiption = new javax.swing.JEditorPane();
        yes1 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        GenRe = new javax.swing.JEditorPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        ReleaseDate = new javax.swing.JEditorPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        BookName = new javax.swing.JEditorPane();
        Header9 = new javax.swing.JLabel();
        ID = new javax.swing.JLabel();
        jDialog2 = new javax.swing.JDialog();
        Header2 = new javax.swing.JLabel();
        yes = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        booklist = new javax.swing.JTable();
        title = new javax.swing.JLabel();
        Header = new javax.swing.JLabel();
        idcheck = new javax.swing.JCheckBox();
        booknamecheck = new javax.swing.JCheckBox();
        authornamecheck = new javax.swing.JCheckBox();
        datecheck = new javax.swing.JCheckBox();
        remove = new javax.swing.JLabel();
        Header1 = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        backL1 = new javax.swing.JLabel();
        edit = new javax.swing.JLabel();
        Header3 = new javax.swing.JLabel();

        jDialog1.setAlwaysOnTop(true);
        jDialog1.setUndecorated(true);
        jDialog1.setSize(new java.awt.Dimension(412, 703));

        Header4.setFont(new java.awt.Font("Footlight MT Light", 1, 20)); // NOI18N
        Header4.setForeground(new java.awt.Color(102, 102, 0));
        Header4.setText("Book Name:");

        Header5.setFont(new java.awt.Font("Footlight MT Light", 1, 20)); // NOI18N
        Header5.setForeground(new java.awt.Color(102, 102, 0));
        Header5.setText("Author Name:");

        Header6.setFont(new java.awt.Font("Footlight MT Light", 1, 20)); // NOI18N
        Header6.setForeground(new java.awt.Color(102, 102, 0));
        Header6.setText("Release Date:");

        Header7.setFont(new java.awt.Font("Footlight MT Light", 1, 20)); // NOI18N
        Header7.setForeground(new java.awt.Color(102, 102, 0));
        Header7.setText("Genre:");

        Header8.setFont(new java.awt.Font("Footlight MT Light", 1, 20)); // NOI18N
        Header8.setForeground(new java.awt.Color(102, 102, 0));
        Header8.setText("Description:");

        jLabel27.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.darkShadow"));
        jLabel27.setFont(new java.awt.Font("Old English Text MT", 0, 24)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(102, 102, 0));
        jLabel27.setText("Book Description");

        AuthorName.setEditable(false);
        AuthorName.setFont(new java.awt.Font("Footlight MT Light", 0, 18)); // NOI18N
        AuthorName.setForeground(new java.awt.Color(102, 102, 0));
        AuthorName.setOpaque(false);
        jScrollPane1.setViewportView(AuthorName);

        DescRiption.setEditable(false);
        DescRiption.setFont(new java.awt.Font("Footlight MT Light", 0, 18)); // NOI18N
        DescRiption.setForeground(new java.awt.Color(102, 102, 0));
        DescRiption.setOpaque(false);
        jScrollPane3.setViewportView(DescRiption);

        yes1.setFont(new java.awt.Font("Footlight MT Light", 0, 20)); // NOI18N
        yes1.setForeground(new java.awt.Color(102, 102, 0));
        yes1.setText("Close");
        yes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yes1ActionPerformed(evt);
            }
        });

        GenRe.setEditable(false);
        GenRe.setFont(new java.awt.Font("Footlight MT Light", 0, 18)); // NOI18N
        GenRe.setForeground(new java.awt.Color(102, 102, 0));
        GenRe.setOpaque(false);
        jScrollPane4.setViewportView(GenRe);

        ReleaseDate.setEditable(false);
        ReleaseDate.setFont(new java.awt.Font("Footlight MT Light", 0, 18)); // NOI18N
        ReleaseDate.setForeground(new java.awt.Color(102, 102, 0));
        ReleaseDate.setOpaque(false);
        jScrollPane5.setViewportView(ReleaseDate);

        BookName.setEditable(false);
        BookName.setFont(new java.awt.Font("Footlight MT Light", 0, 18)); // NOI18N
        BookName.setForeground(new java.awt.Color(102, 102, 0));
        BookName.setOpaque(false);
        jScrollPane6.setViewportView(BookName);

        Header9.setFont(new java.awt.Font("Footlight MT Light", 1, 20)); // NOI18N
        Header9.setForeground(new java.awt.Color(102, 102, 0));
        Header9.setText("Book ID:");

        ID.setFont(new java.awt.Font("Footlight MT Light", 0, 18)); // NOI18N
        ID.setForeground(new java.awt.Color(102, 102, 0));
        ID.setText(" ");

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jLabel27))
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDialog1Layout.createSequentialGroup()
                                .addComponent(Header5)
                                .addGap(3, 3, 3)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(yes1))
                            .addGroup(jDialog1Layout.createSequentialGroup()
                                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Header8)
                                    .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jDialog1Layout.createSequentialGroup()
                                            .addComponent(Header7)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jScrollPane4))
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jDialog1Layout.createSequentialGroup()
                                        .addComponent(Header6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jDialog1Layout.createSequentialGroup()
                                        .addComponent(Header4)
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jDialog1Layout.createSequentialGroup()
                                        .addComponent(Header9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 11, Short.MAX_VALUE)))))
                .addGap(22, 22, 22))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Header4)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Header5)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Header6))
                .addGap(34, 34, 34)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Header7)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Header8)
                .addGap(17, 17, 17)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Header9)
                    .addComponent(ID))
                .addGap(4, 4, 4)
                .addComponent(yes1)
                .addGap(39, 39, 39))
        );

        jDialog2.setAutoRequestFocus(false);
        jDialog2.setBackground(new java.awt.Color(255, 204, 255));
        jDialog2.setUndecorated(true);
        jDialog2.setSize(new java.awt.Dimension(440, 182));

        Header2.setFont(new java.awt.Font("Footlight MT Light", 0, 20)); // NOI18N
        Header2.setForeground(new java.awt.Color(102, 102, 0));
        Header2.setText("Remove the selected books from database?");

        yes.setFont(new java.awt.Font("Footlight MT Light", 0, 20)); // NOI18N
        yes.setForeground(new java.awt.Color(102, 102, 0));
        yes.setText("Yes");
        yes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesActionPerformed(evt);
            }
        });

        cancel.setFont(new java.awt.Font("Footlight MT Light", 0, 20)); // NOI18N
        cancel.setForeground(new java.awt.Color(102, 102, 0));
        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog2Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jDialog2Layout.createSequentialGroup()
                        .addComponent(cancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(yes))
                    .addComponent(Header2))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog2Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(Header2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yes)
                    .addComponent(cancel))
                .addGap(34, 34, 34))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setSize(new java.awt.Dimension(750, 800));

        booklist.setAutoCreateRowSorter(true);
        booklist.setBackground(new java.awt.Color(255, 204, 204));
        booklist.setFont(new java.awt.Font("Footlight MT Light", 0, 18)); // NOI18N
        booklist.setForeground(new java.awt.Color(51, 51, 51));
        booklist.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Book ID", "Book Name", "Author Name", "Genre", "Release Date", "Description"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        booklist.setDropMode(javax.swing.DropMode.INSERT_ROWS);
        booklist.setFillsViewportHeight(true);
        booklist.setGridColor(new java.awt.Color(255, 204, 255));
        booklist.setIntercellSpacing(new java.awt.Dimension(2, 2));
        booklist.setSelectionBackground(new java.awt.Color(204, 204, 255));
        booklist.setSelectionForeground(new java.awt.Color(0, 0, 0));
        booklist.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        booklist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                booklistMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(booklist);
        if (booklist.getColumnModel().getColumnCount() > 0) {
            booklist.getColumnModel().getColumn(0).setPreferredWidth(1);
            booklist.getColumnModel().getColumn(1).setPreferredWidth(60);
            booklist.getColumnModel().getColumn(2).setPreferredWidth(40);
            booklist.getColumnModel().getColumn(3).setPreferredWidth(20);
            booklist.getColumnModel().getColumn(4).setPreferredWidth(40);
            booklist.getColumnModel().getColumn(5).setPreferredWidth(200);
        }

        title.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.darkShadow"));
        title.setFont(new java.awt.Font("Old English Text MT", 0, 30)); // NOI18N
        title.setForeground(new java.awt.Color(153, 102, 0));
        title.setText("View Books");

        Header.setFont(new java.awt.Font("Footlight MT Light", 0, 24)); // NOI18N
        Header.setForeground(new java.awt.Color(51, 51, 51));
        Header.setText("Sort By:");

        sorts.add(idcheck);
        idcheck.setFont(new java.awt.Font("Footlight MT Light", 0, 20)); // NOI18N
        idcheck.setForeground(new java.awt.Color(102, 102, 102));
        idcheck.setText("ID");
        idcheck.setOpaque(false);
        idcheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idcheckActionPerformed(evt);
            }
        });

        sorts.add(booknamecheck);
        booknamecheck.setFont(new java.awt.Font("Footlight MT Light", 0, 20)); // NOI18N
        booknamecheck.setForeground(new java.awt.Color(102, 102, 102));
        booknamecheck.setText("Book Name");
        booknamecheck.setOpaque(false);
        booknamecheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                booknamecheckActionPerformed(evt);
            }
        });

        sorts.add(authornamecheck);
        authornamecheck.setFont(new java.awt.Font("Footlight MT Light", 0, 20)); // NOI18N
        authornamecheck.setForeground(new java.awt.Color(102, 102, 102));
        authornamecheck.setText("Author Name");
        authornamecheck.setOpaque(false);
        authornamecheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                authornamecheckActionPerformed(evt);
            }
        });

        sorts.add(datecheck);
        datecheck.setFont(new java.awt.Font("Footlight MT Light", 0, 20)); // NOI18N
        datecheck.setForeground(new java.awt.Color(102, 102, 102));
        datecheck.setText("Release Date");
        datecheck.setOpaque(false);
        datecheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datecheckActionPerformed(evt);
            }
        });

        remove.setText("jLabel7");
        remove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                removeMouseClicked(evt);
            }
        });

        Header1.setFont(new java.awt.Font("Footlight MT Light", 0, 20)); // NOI18N
        Header1.setForeground(new java.awt.Color(51, 51, 51));
        Header1.setText("Remove Book");
        Header1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Header1MouseClicked(evt);
            }
        });

        back.setFont(new java.awt.Font("Footlight MT Light", 0, 20)); // NOI18N
        back.setForeground(new java.awt.Color(51, 51, 51));
        back.setText("Back");
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });

        backL1.setText("jLabel7");
        backL1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backL1MouseClicked(evt);
            }
        });

        edit.setText("edit");
        edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editMouseClicked(evt);
            }
        });

        Header3.setFont(new java.awt.Font("Footlight MT Light", 0, 20)); // NOI18N
        Header3.setForeground(new java.awt.Color(51, 51, 51));
        Header3.setText("View or Edit");
        Header3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Header3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(datecheck)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Header)
                                .addGap(37, 37, 37)
                                .addComponent(booknamecheck))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(authornamecheck)
                                .addGap(18, 18, 18)
                                .addComponent(idcheck))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(remove, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Header1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(backL1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(back))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(edit, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Header3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 679, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
            .addGroup(layout.createSequentialGroup()
                .addGap(491, 491, 491)
                .addComponent(title)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(title)
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(68, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Header)
                            .addComponent(booknamecheck))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(authornamecheck)
                            .addComponent(idcheck))
                        .addGap(18, 18, 18)
                        .addComponent(datecheck)
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(remove, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Header1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(edit, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Header3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(backL1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(back))
                        .addGap(84, 84, 84))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void removeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeMouseClicked
        jDialog1.setVisible(false);
        jDialog2.setVisible(true);
    }//GEN-LAST:event_removeMouseClicked

    private void backL1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backL1MouseClicked
        jDialog1.setVisible(false);
        this.setVisible(false);this.dispose();
        new BookManagement().setVisible(true);
    }//GEN-LAST:event_backL1MouseClicked

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        jDialog2.setVisible(false);
    }//GEN-LAST:event_cancelActionPerformed

    private void yesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesActionPerformed
        int rowlist = booklist.getSelectedRow();
        int id = (int)((DefaultTableModel)booklist.getModel()).getValueAt(rowlist, 0);
        try {
            db.stmt.executeUpdate("delete from book_genre where book_id= "+id);
            db.stmt.executeUpdate("delete from book where book_id= "+id);
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        jDialog2.setVisible(false);
        this.setVisible(false);this.dispose();
        new ViewBooks().setVisible(true);
    }//GEN-LAST:event_yesActionPerformed

    private void editMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editMouseClicked
        int row = booklist.getSelectedRow();
        int id = (int)((DefaultTableModel)booklist.getModel()).getValueAt(row, 0);
        jDialog1.setVisible(false);
        this.setVisible(false);this.dispose();
        new AddNewBook(id).setVisible(true);
    }//GEN-LAST:event_editMouseClicked

    private void booknamecheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_booknamecheckActionPerformed
        if(booknamecheck.isSelected()){
            setTable("book_name");
        }
    }//GEN-LAST:event_booknamecheckActionPerformed

    private void authornamecheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_authornamecheckActionPerformed
        if(authornamecheck.isSelected()){
            setTable("author_name");
        }
    }//GEN-LAST:event_authornamecheckActionPerformed

    private void datecheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datecheckActionPerformed
        if(datecheck.isSelected()){
            setTable("release_date");
        }
    }//GEN-LAST:event_datecheckActionPerformed

    private void idcheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idcheckActionPerformed
        if(idcheck.isSelected()){
            setTable("book_id");
        }
    }//GEN-LAST:event_idcheckActionPerformed

    private void yes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yes1ActionPerformed
        jDialog1.setVisible(false);
    }//GEN-LAST:event_yes1ActionPerformed

    private void booklistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_booklistMouseClicked
        int row = booklist.getSelectedRow();
        ID.setText(((DefaultTableModel)booklist.getModel()).getValueAt(row, 0).toString());
        BookName.setText(((DefaultTableModel)booklist.getModel()).getValueAt(row, 1).toString());
        AuthorName.setText(((DefaultTableModel)booklist.getModel()).getValueAt(row, 2).toString());
        GenRe.setText(((DefaultTableModel)booklist.getModel()).getValueAt(row, 3).toString());
        ReleaseDate.setText(((DefaultTableModel)booklist.getModel()).getValueAt(row, 4).toString());
        DescRiption.setText(((DefaultTableModel)booklist.getModel()).getValueAt(row, 5).toString());
        jDialog1.setVisible(true);
    }//GEN-LAST:event_booklistMouseClicked

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        jDialog1.setVisible(false);
        this.setVisible(false);this.dispose();
        new BookManagement().setVisible(true);
    }//GEN-LAST:event_backMouseClicked

    private void Header3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Header3MouseClicked
        int row = booklist.getSelectedRow();
        int id = (int)((DefaultTableModel)booklist.getModel()).getValueAt(row, 0);
        jDialog1.setVisible(false);
        this.setVisible(false);this.dispose();
        new AddNewBook(id).setVisible(true);
    }//GEN-LAST:event_Header3MouseClicked

    private void Header1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Header1MouseClicked
        jDialog1.setVisible(false);
        jDialog2.setVisible(true);
    }//GEN-LAST:event_Header1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewBooks().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane AuthorName;
    private javax.swing.JEditorPane BookName;
    private javax.swing.JEditorPane DescRiption;
    private javax.swing.JEditorPane GenRe;
    private javax.swing.JLabel Header;
    private javax.swing.JLabel Header1;
    private javax.swing.JLabel Header2;
    private javax.swing.JLabel Header3;
    private javax.swing.JLabel Header4;
    private javax.swing.JLabel Header5;
    private javax.swing.JLabel Header6;
    private javax.swing.JLabel Header7;
    private javax.swing.JLabel Header8;
    private javax.swing.JLabel Header9;
    private javax.swing.JLabel ID;
    private javax.swing.JEditorPane ReleaseDate;
    private javax.swing.JCheckBox authornamecheck;
    private javax.swing.JLabel back;
    private javax.swing.JLabel backL1;
    private javax.swing.JTable booklist;
    private javax.swing.JCheckBox booknamecheck;
    private javax.swing.JButton cancel;
    private javax.swing.JCheckBox datecheck;
    private javax.swing.JLabel edit;
    private javax.swing.JCheckBox idcheck;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel remove;
    private javax.swing.ButtonGroup sorts;
    private javax.swing.JLabel title;
    private javax.swing.JButton yes;
    private javax.swing.JButton yes1;
    // End of variables declaration//GEN-END:variables
}
